### ISSUE TITLE
Not an issue, per se, but how can i do this?

### ISSUE THREAD

**Issue by LinuxTerrorist** [LightAir/darkmini#14]
Hey! I created a few icons for OSes that don't exist in the Darkmini install that suits my purposes. Tried to find a way to get a hold of the original poster in order to submit them. Any suggestions?

**Comment by LightAir** [comment]
Hi! You can use the [source/os_template.svg](https://github.com/LightAir/darkmini/blob/master/source/os_template.svg) template. Add everything you need and send me PR. Don't worry if something is not up to “standard” I will fix it in the next release.
Or you can send me the icons and I will add them in the near future

**Comment by TomGooner** [comment]
Thank you for your work on this. Would it be possible to get icons for CachyOS and Endeavour? I'm unfortunately not much of an artist myself.

**Comment by LinuxTerrorist** [comment]
TomGooner, I have created one for Endeavour. I will see if I can also do one for Catchy in the next few days and then will forward them all to Lightair.

**Comment by LinuxTerrorist** [comment]
![os_commodore](https://github.com/user-attachments/assets/62d86539-d511-41de-b1b4-9e0b56eb410b)
![os_cachy](https://github.com/user-attachments/assets/13abe56a-05a2-409c-b78a-e3c98ca7bcb0)
![os_fyde](https://github.com/user-attachments/assets/3bba317f-ee93-4641-97c2-8a6f1b6978a5)
![os_pop](https://github.com/user-attachments/assets/c7ebee44-9a7e-4ba2-bdc9-822982af4a98)
![os_mxlinux](https://github.com/user-attachments/assets/17c4e474-1cf3-421f-9b59-16e258811e38)
![os_endeavour](https://github.com/user-attachments/assets/7549fd17-67bc-48cf-9caf-e78841ed7be9)
![os_tuxedo](https://github.com/user-attachments/assets/8b2373d5-0ba0-4df6-92ad-c5c4fead9d98)
![os_garuda](https://github.com/user-attachments/assets/7e5ac7f3-1f92-4246-9e6d-c344df3fbe82)
![os_zorin](https://github.com/user-attachments/assets/979b2b54-8c62-4dbb-803a-7b25885d356d)

**Comment by LinuxTerrorist** [comment]
Lightair, not exactly the best but here is what I have. If you need me to redo any of them, please let me know :)

**Comment by LinuxTerrorist** [comment]
![os_zorin](https://github.com/user-attachments/assets/5633dc52-aa66-4820-a084-d44d4da75186)

**Comment by LinuxTerrorist** [comment]
Sorry, the earlier one for Zorin was an older file...here's a newer one.

**Comment by LinuxTerrorist** [comment]
This one for Nobara seems a little thick but thought I'd throw it up anyhow since I just installed the OS and cobbled-together the icon...
![os_nobara](https://github.com/user-attachments/assets/8b5a276b-f5a7-49c9-a4e2-ac063ce831b7)

**Comment by LightAir** [comment]
Hi. Nobara, zorinos, mxlinux are already present in the package ([mxlinux](https://github.com/LightAir/darkmini/blob/master/icons/os_mxlinux.png), [zorinos](https://github.com/LightAir/darkmini/blob/master/icons/os_zorinos.png), [osnobara](https://github.com/LightAir/darkmini/blob/master/icons/os_nobara.png)). If they are not displayed, then maybe the name of the directory where the efi files are installed does not match the name of the icon. Here is from the official refind site “You can place a boot loader in a directory with a name that matches one of rEFInd's standard icons, which take names of the form os_name.icns or os_name.png. To use such an icon, you would place the boot loader in the directory called name. For instance, the boot loader in the EFI/freebsd directory will use rEFInd's os_freebsd.png icon."”
I will try to check and in case of inconsistency of OS picture names to correct the names. 
As for the rest of the pictures, for some reason they don't seem to be smoothed out and a bit offset.

If it doesn't upset you, I could draw and add to package my own version of the icons

**Comment by LightAir** [comment]
Done. I've added new icons

https://github.com/LightAir/darkmini/releases/tag/v2.2.0

**Comment by LinuxTerrorist** [comment]
Glad I could help. Lol.

**Comment by LinuxTerrorist** [comment]
Great job on the theme and good job!
