### ISSUE TITLE
add nobara linux icon

### ISSUE THREAD

**Issue by VPraharsha03** [LightAir/darkmini#8]
please add nobara linux icon

**Comment by VPraharsha03** [comment]
@LightAir what is the progress ? if you want I can share the .svg in case

**Comment by LightAir** [comment]
@VPraharsha03 Hi. Added a nobara linux icon #9 

https://github.com/LightAir/darkmini/blob/3e5682dcbfc78d6d7b3d8c1ae49c71465cd95590/icons/os_nobara.png

**Comment by LightAir** [comment]
> if possible please share us the script/template for creating our own pngs from svgs, thanks.

There is no template as such. The main thing is that the result would be a png file of size 128x128 px in the center of which the icon is about half the size.

You can take as a sample some svg file, for example [source/os_mint.svg](https://github.com/LightAir/darkmini/blob/e798fec5d2e34056280a5f594c4e378d2c9e8fb9/source/os_mint.svg)

**Comment by VPraharsha03** [comment]
> > if possible please share us the script/template for creating our own pngs from svgs, thanks.
> 
> There is no template as such. The main thing is that the result would be a png file of size 128x128 px in the center of which the icon is about half the size.
> 
> You can take as a sample some svg file, for example [source/os_mint.svg](https://github.com/LightAir/darkmini/blob/e798fec5d2e34056280a5f594c4e378d2c9e8fb9/source/os_mint.svg)
> 

yes I observed that canvas is 128x128, but I didn't know how much to actually scale down the logo

**Comment by VPraharsha03** [comment]
> @VPraharsha03 Hi. Added a nobara linux icon #9 
> 
> https://github.com/LightAir/darkmini/blob/3e5682dcbfc78d6d7b3d8c1ae49c71465cd95590/icons/os_nobara.png

@LightAir Thank you! I feel that nobara icon looks slightly bigger than rest of the icons

**Comment by LightAir** [comment]
@VPraharsha03 Yes, thank you. I thought it would be a good idea to bring the icons to the same size. Made a template and followed it. It seems to look better now. https://github.com/LightAir/darkmini/releases
